---
title: "Dashing diamonds"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    css: bootswatch-3.3.5-4/flatly/bootstrap.css
    source_code: embed
runtime: shiny
---
```{r}
library(flexdashboard)
```

Exploratory plots 
=======================================================================

Sidebar {.sidebar data-width=250} 
-----------------------------------------------------------------------

**Exploratory plots**


**Scatterplots**


**Density plot**


**Summary statistics**

Row 
-----------------------------------------------------------------------

### Maximum carats {data-width=50}
```{r}
valueBox(
  78, icon = "fa-trash",
  color = ifelse(78 > 10, "warning", "primary")
)
```

### Most expensive color {data-width=50}
```{r}
valueBox(
  35, icon = "fa-trash",
  color = ifelse(78 > 10, "warning", "primary")
)
```

### Maximal price {data-width=50}
```{r}
valueBox(
  10, icon = "fa-trash",
  color = ifelse(78 > 10, "warning", "primary")
)
```


Row {.tabset}
-----------------------------------------------------------------------

### Scatterplot of selected variables

### Density plot for selected variable


Row {data-height=500}
-----------------------------------------------------------------------

### Summary statistics {data-width=500}

Model comparison
=======================================================================

Sidebar {.sidebar data-width=250}
-----------------------------------------------------------------------

**Model comparison**

<br>

Row{.tabset}
-----------------------------------------------------------------------

 **Comparison of Predictions and Target**

### Linear Model

### Ridge Regression 

Row
-----------------------------------------------------------------------
### Densities of predictions vs. target 